#!/bin/bash

yum update -y
sudo yum install centos-release-scl
sudo yum-config-manager --enable rhel-server-rhscl-7-rpms
sudo yum install rh-ruby22
scl enable rh-ruby22 bash



# yum install ruby
gem install sinatra
